[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = postgres-container
db_port = 5432
db_user = celiani
db_password = qui8Tiv
db_name = celiani_db
addons_path = /mnt/extra-addons
logfile = /var/log/odoo/odoo.log
